{
  "hash": "1eaa81567495f1cb56e9d715e746c254",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A3: Grades\"\nauthor: \"Tanya Michelle Justin\"\n---\n\n\n\n## **Art, Design, and Vocation are all diff-different.**\n\n### What are we trying to find out?\n\nThe purpose of this experiment is to see whether there is a significant differences in grades between students enrolled in different degree programs at Srishti. We will be evaluating based on the three types of degress which are B.Voc, B.FA, and B.Des.\n\n### How was the data collected?\n\nThe sample data for this study was collected from students at Srishti who were available at the time of data gathering. To minimize selection bias, participants were chosen through a coin toss, which determined whether each student would participate in the survey. This sample aims to represent the entire Srishti student population. This data was gathered from 90 individuals, ensuring a balanced sample of 30 B.Voc, 30 B.FA and 30 B.Des students, with an equal number of male and female participants to eliminate potential gender bias. Each student was asked about their grades in their last cycle and which course they took as well.\n\nI believe that if we were to conduct this test again, it would be beneficial to ensure that we have equal samples from each course or maintain an equal ratio compared to the population. This would help eliminate any potential course bias in the data and provide a more accurate representation of the overall population.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(skimr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(crosstable)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(infer) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'infer'\n\nThe following objects are masked from 'package:mosaic':\n\n    prop_test, t_test\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(patchwork) \nlibrary(ggprism)\nlibrary(supernova) \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades <- read.csv(\"../../data/Grades.csv\")\ngrades\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   SN Degree Course Year Letter.Grade Score Gender\n1   1  B.Des    CAC    2            A   8.0      F\n2   2  B.Des    CAC    2            O   9.6      F\n3   3  B.Des   IADP    2           A+   9.2      F\n4   4  B.Des     CE    2            O   9.8      F\n5   5  B.Des   BSSD    2            P   3.0      M\n6   6  B.Des    CAC    2            O   9.5      F\n7   7  B.Des    PSD    2           A+   9.0      F\n8   8  B.Des    PSD    2           A+   9.0      F\n9   9  B.Des    PSD    2           A+   9.0      F\n10 10  B.Des   BSSD    3           A+   9.0      F\n11 11  B.Des   VCSB    2            A   8.0      F\n12 12  B.Des   VCSB    2            A   8.0      F\n13 13  B.Des  IAIDP    3            A   8.0      M\n14 14  B.Des  IAIDP    3           B+   7.0      M\n15 15  B.Des   VCSB    2           B+   7.0      F\n16 16  B.Des    HCD    3           A+   9.0      M\n17 17  B.Des    CAC    3           A+   9.1      F\n18 18  B.Des   VCSB    2            A   8.0      M\n19 19  B.Des     CE    2           A+   9.0      F\n20 20  B.Des    CAC    2           A+   9.0      M\n21 21  B.Des   IADP    2            A   8.0      F\n22 22  B.Des   IADP    3           B+   7.0      M\n23 23  B.Des   VCSB    3           A+   9.0      F\n24 24  B.Des     CE    2            O  10.0      F\n25 25  B.Des    CAC    3           A+   9.0      F\n26 26  B.Des    CAC    3           A+   9.0      F\n27 27  B.Des    PSD    3           B+   7.0      F\n28 28  B.Des    PSD    3            A   8.0      F\n29 29  B.Des    CAC    2           A+   9.0      F\n30 30  B.Des    HCD    2            A   8.0      F\n31 31  B.Voc   UIID    3            O   9.5      F\n32 32  B.Voc   UIID    3           A+   9.0      F\n33 33  B.Voc   UIID    3           A+   9.0      M\n34 34  B.Voc   UIID    3           B+   7.0      M\n35 35  B.Voc   UIID    3            A   8.0      F\n36 36  B.Voc   UIID    3            A   8.0      F\n37 37  B.Voc     ID    3           B+   7.0      M\n38 38  B.Voc    DMP    3            O   9.5      M\n39 39  B.Voc    DMP    3            B   6.5      M\n40 40  B.Voc    DMP    3            O   9.5      M\n41 41  B.Voc    DMP    3            O   9.5      M\n42 42  B.Voc    DMP    3           A+   9.0      M\n43 43  B.Voc    DMP    3            O   9.5      F\n44 44  B.Voc    DMP    3            O   9.5      F\n45 45  B.Voc    DMP    3            B   6.5      F\n46 46  B.Voc    DMP    3            C   5.0      M\n47 47  B.Voc   UIID    1           A+   9.0      M\n48 48  B.Voc   UIID    1            B   7.0      F\n49 49  B.Voc   UIID    1            B   7.0      F\n50 50  B.Voc   UIID    1            A   8.0      F\n51 51  B.Voc   UIID    1            A   8.0      F\n52 52  B.Voc   UIID    1           A+   9.0      F\n53 53  B.Voc   UIID    2            A   8.0      M\n54 54  B.Voc   GADP    1            A   8.0      F\n55 55  B.Voc   GADP    2            A   8.0      M\n56 56  B.Voc   Film    3            A   8.0      M\n57 57  B.Voc   GADP    3           A+   9.0      F\n58 58  B.Voc   GADP    3           A+   9.0      F\n59 59  B.Voc    DMP    2            A   8.0      M\n60 60  B.Voc    DMP    2            A   8.0      M\n61 61   B.FA    CAP    3            A   8.0      F\n62 62   B.FA    CAP    3           A+   9.0      M\n63 63   B.FA    CAP    3           A+   9.0      F\n64 64   B.FA    DMA    2           A+   8.5      M\n65 65   B.FA    DMA    2            A   8.0      M\n66 66   B.FA    DMA    2            A   8.0      F\n67 67   B.FA    CAP    2            A   8.0      F\n68 68   B.FA    CAP    2           A+   8.0      F\n69 69   B.FA   Film    3            B   6.0      M\n70 70   B.FA    DMA    2            A   8.0      F\n71 71   B.FA    DMA    2           B+   7.0      F\n72 72   B.FA    DMA    2           B+   7.0      F\n73 73   B.FA    DMA    2            A   8.0      F\n74 74   B.FA    DMA    2           B+   7.0      F\n75 75   B.FA    DMA    2            B   6.0      M\n76 76   B.FA   Film    3            A   8.0      M\n77 77   B.FA   Film    3            A   8.0      M\n78 78   B.FA    DMA    2            A   8.0      M\n79 79   B.FA    DMA    2            A   8.0      M\n80 80   B.FA    DMA    2           B+   7.0      F\n81 81   B.FA    DMA    2           B+   7.0      F\n82 82   B.FA   Film    2            A   8.0      F\n83 83   B.FA   Film    3           B+   7.0      F\n84 84   B.FA    DMA    2           A+   9.0      F\n85 85   B.FA    DMA    2            A   8.0      M\n86 86   B.FA    DMA    2           B+   7.0      F\n87 87   B.FA    DMA    2           B+   7.0      F\n88 88   B.FA    DMA    2           B+   7.0      M\n89 89   B.FA    DMA    2           B+   7.0      F\n90 90   B.FA    DMA    2           B+   7.0      F\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(grades)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 90\nColumns: 7\n$ SN           <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17…\n$ Degree       <chr> \"B.Des\", \"B.Des\", \"B.Des\", \"B.Des\", \"B.Des\", \"B.Des\", \"B.…\n$ Course       <chr> \"CAC\", \"CAC\", \"IADP\", \"CE\", \"BSSD\", \"CAC\", \"PSD\", \"PSD\", …\n$ Year         <int> 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 2, 3, 3, 2, 2, …\n$ Letter.Grade <chr> \"A\", \"O\", \"A+\", \"O\", \"P\", \"O\", \"A+\", \"A+\", \"A+\", \"A+\", \"A…\n$ Score        <dbl> 8.0, 9.6, 9.2, 9.8, 3.0, 9.5, 9.0, 9.0, 9.0, 9.0, 8.0, 8.…\n$ Gender       <chr> \"F\", \"F\", \"F\", \"F\", \"M\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ninspect(grades)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\ncategorical variables:  \n          name     class levels  n missing\n1       Degree character      3 90       0\n2       Course character     15 90       0\n3 Letter.Grade character      7 90       0\n4       Gender character      2 90       0\n                                   distribution\n1 B.Des (33.3%), B.FA (33.3%) ...              \n2 DMA (22.2%), UIID (14.4%), DMP (12.2%) ...   \n3 A (33.3%), A+ (27.8%), B+ (18.9%) ...        \n4 F (63.3%), M (36.7%)                         \n\nquantitative variables:  \n   name   class min    Q1 median    Q3 max      mean         sd  n missing\n1    SN integer   1 23.25   45.5 67.75  90 45.500000 26.1247010 90       0\n2  Year integer   1  2.00    2.0  3.00   3  2.333333  0.6180797 90       0\n3 Score numeric   3  7.00    8.0  9.00  10  8.063333  1.1346880 90       0\n```\n\n\n:::\n:::\n\n\n\n### Data Dictionary:\n\n-   Qualitative Data:\n    -   Degree\n\n    -   Course\n\n    -   Letter Grade\n\n    -   Gender\n-   Quantitative Data:\n    -   Score\n    -   Year\n\n*Target Variable* : Score\n\n*Predictor* *Variable* : Degree\n\n### Mutating and plotting the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_modified <- grades %>%\n  dplyr::mutate(\n    Gender = as_factor(Gender),\n    Year = factor(Year,\n      levels = c(\"1\",\"2\",\"3\"),\n      labels = c(\"1\",\"2\",\"3\"),\n      ordered = TRUE),\n    Degree = as_factor(Degree),\n    Course = as_factor(Course)\n    )%>%\n  select(Degree , Course, Year, Gender, Score)\ngrades_modified\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Degree Course Year Gender Score\n1   B.Des    CAC    2      F   8.0\n2   B.Des    CAC    2      F   9.6\n3   B.Des   IADP    2      F   9.2\n4   B.Des     CE    2      F   9.8\n5   B.Des   BSSD    2      M   3.0\n6   B.Des    CAC    2      F   9.5\n7   B.Des    PSD    2      F   9.0\n8   B.Des    PSD    2      F   9.0\n9   B.Des    PSD    2      F   9.0\n10  B.Des   BSSD    3      F   9.0\n11  B.Des   VCSB    2      F   8.0\n12  B.Des   VCSB    2      F   8.0\n13  B.Des  IAIDP    3      M   8.0\n14  B.Des  IAIDP    3      M   7.0\n15  B.Des   VCSB    2      F   7.0\n16  B.Des    HCD    3      M   9.0\n17  B.Des    CAC    3      F   9.1\n18  B.Des   VCSB    2      M   8.0\n19  B.Des     CE    2      F   9.0\n20  B.Des    CAC    2      M   9.0\n21  B.Des   IADP    2      F   8.0\n22  B.Des   IADP    3      M   7.0\n23  B.Des   VCSB    3      F   9.0\n24  B.Des     CE    2      F  10.0\n25  B.Des    CAC    3      F   9.0\n26  B.Des    CAC    3      F   9.0\n27  B.Des    PSD    3      F   7.0\n28  B.Des    PSD    3      F   8.0\n29  B.Des    CAC    2      F   9.0\n30  B.Des    HCD    2      F   8.0\n31  B.Voc   UIID    3      F   9.5\n32  B.Voc   UIID    3      F   9.0\n33  B.Voc   UIID    3      M   9.0\n34  B.Voc   UIID    3      M   7.0\n35  B.Voc   UIID    3      F   8.0\n36  B.Voc   UIID    3      F   8.0\n37  B.Voc     ID    3      M   7.0\n38  B.Voc    DMP    3      M   9.5\n39  B.Voc    DMP    3      M   6.5\n40  B.Voc    DMP    3      M   9.5\n41  B.Voc    DMP    3      M   9.5\n42  B.Voc    DMP    3      M   9.0\n43  B.Voc    DMP    3      F   9.5\n44  B.Voc    DMP    3      F   9.5\n45  B.Voc    DMP    3      F   6.5\n46  B.Voc    DMP    3      M   5.0\n47  B.Voc   UIID    1      M   9.0\n48  B.Voc   UIID    1      F   7.0\n49  B.Voc   UIID    1      F   7.0\n50  B.Voc   UIID    1      F   8.0\n51  B.Voc   UIID    1      F   8.0\n52  B.Voc   UIID    1      F   9.0\n53  B.Voc   UIID    2      M   8.0\n54  B.Voc   GADP    1      F   8.0\n55  B.Voc   GADP    2      M   8.0\n56  B.Voc   Film    3      M   8.0\n57  B.Voc   GADP    3      F   9.0\n58  B.Voc   GADP    3      F   9.0\n59  B.Voc    DMP    2      M   8.0\n60  B.Voc    DMP    2      M   8.0\n61   B.FA    CAP    3      F   8.0\n62   B.FA    CAP    3      M   9.0\n63   B.FA    CAP    3      F   9.0\n64   B.FA    DMA    2      M   8.5\n65   B.FA    DMA    2      M   8.0\n66   B.FA    DMA    2      F   8.0\n67   B.FA    CAP    2      F   8.0\n68   B.FA    CAP    2      F   8.0\n69   B.FA   Film    3      M   6.0\n70   B.FA    DMA    2      F   8.0\n71   B.FA    DMA    2      F   7.0\n72   B.FA    DMA    2      F   7.0\n73   B.FA    DMA    2      F   8.0\n74   B.FA    DMA    2      F   7.0\n75   B.FA    DMA    2      M   6.0\n76   B.FA   Film    3      M   8.0\n77   B.FA   Film    3      M   8.0\n78   B.FA    DMA    2      M   8.0\n79   B.FA    DMA    2      M   8.0\n80   B.FA    DMA    2      F   7.0\n81   B.FA    DMA    2      F   7.0\n82   B.FA   Film    2      F   8.0\n83   B.FA   Film    3      F   7.0\n84   B.FA    DMA    2      F   9.0\n85   B.FA    DMA    2      M   8.0\n86   B.FA    DMA    2      F   7.0\n87   B.FA    DMA    2      F   7.0\n88   B.FA    DMA    2      M   7.0\n89   B.FA    DMA    2      F   7.0\n90   B.FA    DMA    2      F   7.0\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_modified %>%\n  gf_histogram(~Score, fill = ~Degree) %>% \n  gf_labs(title= \"Plotting Scores and facetting with Degree\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_modified %>%\n  gf_histogram(~Score, fill = ~Degree) %>% \n  gf_labs(title = \"Distribution of Scores by Degree\") %>%\n  gf_facet_wrap(~Degree)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggformula)\n\ngrades_modified %>%\n  gf_histogram(~Score, fill = ~Degree, position = \"fill\") %>%\n  gf_labs(title = \"Distribution of Scores by Degree\") +\n  coord_flip()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 42 rows containing missing values or values outside the scale range\n(`geom_bar()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_modified %>%\n  gf_density(\n    ~ Score,\n    fill = ~ Degree,\n    alpha = 0.5,\n    title = \"Grades Densities by Degrees \",\n    subtitle = \"B.Des vs B.Voc us B.FA\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n*Observations*:\n\nAs I can see from the graphs B.Des looks like it gets higher grades compared to the other degrees however all values of B.FA are normally above score\\>6.\n\n### Crosstables\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrosstable(Score ~ Degree, data = grades_modified) %>%\n  crosstable::as_flextable()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-c2afbcc2{table-layout:auto;}.cl-c2ad0126{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-c2ad0130{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-c2ae1a34{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-c2ae1a35{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-c2ae26aa{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c2ae26ab{background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c2ae26ac{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c2ae26b4{background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-c2ae26b5{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-c2afbcc2'><thead><tr style=\"overflow-wrap:break-word;\"><th  rowspan=\"2\"class=\"cl-c2ae26aa\"><p class=\"cl-c2ae1a34\"><span class=\"cl-c2ad0126\">label</span></p></th><th  rowspan=\"2\"class=\"cl-c2ae26aa\"><p class=\"cl-c2ae1a34\"><span class=\"cl-c2ad0126\">variable</span></p></th><th  colspan=\"3\"class=\"cl-c2ae26ab\"><p class=\"cl-c2ae1a34\"><span class=\"cl-c2ad0126\">Degree</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-c2ae26ac\"><p class=\"cl-c2ae1a34\"><span class=\"cl-c2ad0126\">B.Des</span></p></th><th class=\"cl-c2ae26ac\"><p class=\"cl-c2ae1a34\"><span class=\"cl-c2ad0126\">B.Voc</span></p></th><th class=\"cl-c2ae26ac\"><p class=\"cl-c2ae1a34\"><span class=\"cl-c2ad0126\">B.FA</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td  rowspan=\"4\"class=\"cl-c2ae26b4\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">Score</span></p></td><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">Min / Max</span></p></td><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">3.0 / 10.0</span></p></td><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">5.0 / 9.5</span></p></td><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">6.0 / 9.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">Med [IQR]</span></p></td><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">9.0 [8.0;9.0]</span></p></td><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">8.0 [8.0;9.0]</span></p></td><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">8.0 [7.0;8.0]</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">Mean (std)</span></p></td><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">8.4 (1.3)</span></p></td><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">8.2 (1.1)</span></p></td><td class=\"cl-c2ae26b5\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">7.6 (0.8)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-c2ae26b4\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">N (NA)</span></p></td><td class=\"cl-c2ae26b4\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">30 (0)</span></p></td><td class=\"cl-c2ae26b4\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">30 (0)</span></p></td><td class=\"cl-c2ae26b4\"><p class=\"cl-c2ae1a35\"><span class=\"cl-c2ad0130\">30 (0)</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n*Observations*:\n\nWhile the mean scores across degrees i appear to differ, this visible difference alone is not enough to conclude that the difference in means is significant.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_modified %>%\n  gf_boxplot(Degree ~ Score, fill = ~Degree, alpha=0.5) %>%\n  gf_labs(title = \"Box plot of Scores by Degree\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n### Anova\n\nANOVA over here is a method used to compare the average grades of students across different degree programs to see if there are significant differences in their performance. In this case, ANOVA tests the idea that the average grades for all degree programs are the same, considering degree type as a factor influencing grades. Typically, a One-Way ANOVA is used, with grades as the continuous variable and degree as the categorical variable. Key assumptions include that the data points are independent, grades are normally distributed within each degree group, and the variances are similar across groups. The ANOVA results include an F-statistic and a p-value, where a p-value below 0.05 suggests that at least one degree program's average grade is different from the others.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_anova <- aov(Score ~ Degree, data = grades_modified) \ngrades_supernova <- supernova::pairwise(grades_anova,\n  correction = \"Bonferroni\",\n  alpha = 0.05, # 95% CI calculation\n  var_equal = TRUE, \n  plot = TRUE\n) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\ngrades_supernova\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Pairwise t-tests with Bonferroni correction ─────────────────────────────────\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nModel: Score ~ Degree\n```\n\n\n:::\n\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDegree\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLevels: 3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFamily-wise error-rate: 0.049\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  group_1 group_2   diff pooled_se      t    df  lower  upper  p_adj\n  <chr>   <chr>    <dbl>     <dbl>  <dbl> <int>  <dbl>  <dbl>  <dbl>\n1 B.Voc   B.Des   -0.173     0.201 -0.864    87 -0.607  0.261 1.0000\n2 B.FA    B.Des   -0.757     0.201 -3.770    87 -1.191 -0.323  .0009\n3 B.FA    B.Voc   -0.583     0.201 -2.906    87 -1.017 -0.149  .0139\n```\n\n\n:::\n:::\n\n\n\n*Observations*:\n\nThe output shows the results of pairwise comparisons of average grades between different degree programs. For example, the comparison between **B.Voc** and **B.Des** has a mean difference of **-0.173**, suggesting that students in **B.Voc** tend to have lower average grades than those in **B.Des**. the pooled standard error of **0.201** and the t-value of **-0.864** indicate that the difference in means between the two groups is relatively small compared to the variability of the sample means. Given that the t-value is not large enough to reach a critical threshold for significance, this suggests that the difference is not statistically significant. The confidence interval for this difference ranges from **-0.607** to **0.261**, indicating that the difference is not statistically significant since the interval includes zero. Similar interpretations apply to the other comparisons, showing no significant differences among the degree programs based on the data.\n\n### Shapiro Test\n\nDetermining whether the data is normal or not.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(x = grades_modified$Score) %>%\n    broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  statistic     p.value method                     \n      <dbl>       <dbl> <chr>                      \n1     0.885 0.000000920 Shapiro-Wilk normality test\n```\n\n\n:::\n:::\n\n\n\n*Observations*:\n\nSince the p-value is significantly less than 0.05, this suggests that the data does not follow a normal distribution.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_modified %>%\n  group_by(Degree) %>%\n  group_modify(~ .x %>%\n    select(Score) %>%\n    as_vector() %>%\n    shapiro.test() %>%\n    broom::tidy())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n# Groups:   Degree [3]\n  Degree statistic   p.value method                     \n  <fct>      <dbl>     <dbl> <chr>                      \n1 B.Des      0.753 0.0000101 Shapiro-Wilk normality test\n2 B.Voc      0.887 0.00418   Shapiro-Wilk normality test\n3 B.FA       0.875 0.00211   Shapiro-Wilk normality test\n```\n\n\n:::\n:::\n\n\n\n*Observations*:\n\nSince all p-values are less than 0.05, we reject the null hypothesis for all three groups, suggesting that the data for these degree programs do not follow a normal distribution. Hence, we should further analyse this sample (Permutation Test).\n\n### Plotting this\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_modified %>%\n  gf_density( ~ Score,\n              fill = ~ Degree,\n              alpha = 0.5,\n              title = \"Score of different degrees vs normal distribution\") %>%\n  gf_facet_grid(~ Degree) %>% \n  gf_fitdistr(dist = \"dnorm\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n### Test for Variance\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_modified %>%\n  group_by(Degree) %>%\n  summarise(variance = var(Score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  Degree variance\n  <fct>     <dbl>\n1 B.Des     1.74 \n2 B.Voc     1.27 \n3 B.FA      0.615\n```\n\n\n:::\n:::\n\n\n\n*Observations*:\n\nThe B.Des program exhibits the highest variance, with a value of 1.7, while the B.FA program has the lowest variance at 0.6. Given that our data does not follow a normal distribution, I can apply the Fligner-Killeen test to assess the homogeneity of variances among the different groups.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfligner.test(Score ~ Degree, data = grades_modified)%>%\n    broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  statistic p.value parameter method                                          \n      <dbl>   <dbl>     <dbl> <chr>                                           \n1      2.27   0.321         2 Fligner-Killeen test of homogeneity of variances\n```\n\n\n:::\n:::\n\n\n\n*Observations*:\n\nThe results of the Fligner-Killeen test indicate that there is no significant difference in variances among the groups (p-value = 0.321309). This suggests that the assumption of homogeneity of variances holds for the data, which is an important consideration for conducting further statistical analyses, such as ANOVA.\n\n### ANOVA using Permutation Tests\n\nPermutation tests are distribution-free, meaning they do not rely on specific assumptions regarding the underlying data distribution, such as normality and homogeneity of variances. This is particularly useful since we have already rejected the assumption of equal variances, as well as normality.\n\nOur goal is to determine whether Grades depend on Degree or if the differences we observe might simply be due to random chance. The F-statistic quantifies the extent of variation between the groups (based on degree levels) relative to the variation within each group.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_infer <-\n  grades_modified %>%\n  specify(Score ~ Degree) %>%\n  hypothesise(null = \"independence\") %>%\n  calculate(stat = \"F\")\nobserved_infer\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: Score (numeric)\nExplanatory: Degree (factor)\nNull Hypothesis: independence\n# A tibble: 1 × 1\n   stat\n  <dbl>\n1  3.90\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist_infer <- grades_modified %>%\n  specify(Score ~ Degree) %>%\n  hypothesise(null = \"independence\") %>%\n  generate(reps = 4999, type = \"permute\") %>%\n  calculate(stat = \"F\")\n##\nnull_dist_infer\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: Score (numeric)\nExplanatory: Degree (factor)\nNull Hypothesis: independence\n# A tibble: 4,999 × 2\n   replicate  stat\n       <int> <dbl>\n 1         1 0.111\n 2         2 0.192\n 3         3 2.73 \n 4         4 1.77 \n 5         5 0.808\n 6         6 0.847\n 7         7 0.135\n 8         8 0.770\n 9         9 0.760\n10        10 0.444\n# ℹ 4,989 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist_infer %>%\n  visualise(method = \"simulation\") +\n  shade_p_value(obs_stat = observed_infer$stat, direction = \"right\") +\n  scale_x_continuous(trans = \"log10\", expand = c(0, 0)) +\n  coord_cartesian(xlim = c(0.2, 500), clip = \"off\") +\n  annotation_logticks(outside = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in transformation$transform(x): NaNs produced\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in scale_x_continuous(trans = \"log10\", expand = c(0, 0)): log-10\ntransformation introduced infinite values.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np_value <- null_dist_infer %>%\n  summarise(p_value = mean(stat >= observed_infer$stat))\np_value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  p_value\n    <dbl>\n1  0.0236\n```\n\n\n:::\n:::\n\n\n\n### Conclusion \n\nA p-value of 0.019 suggests there is only a 1.9% chance of obtaining these results if Degree had no impact on Score. Given the low p-value, we can reject the null hypothesis that states there are no differences in the grades of students from various degree programs.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}